apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCBDNovMrxt5CsbV4cAaVZTPg/7uArEi9W/oM0NctzBSo+6eOkDFtQzsRDVrfWAsCmf+Krb8fqGbxQ4jWKeEHXowUewlnRi58iR9popHsI8BSgAcumUfR7p+P5l+SHNBvqoA8NqQa72qRaIgOOFo9gYt9db336mSrm4cCnEpaHEICjkswJxCn6iTa3H1XYLCp+6AmWs5+LHWoaYEimw1OilHxce8UGZJH3CwJZrp5KCLFM3BPEFJ1ovF6qzdavfwTuE0mBfQMvReEmodbkc8ftk2F+4pWTCsVRKmzdY/YG4V2HweZr2jCshkfZUz08VAlMASebdnlj1srX4J1Z/REWno1zL73zfK2zYKse5I8ImNMaHixjRI4t7Y2rcVWtLJE50fhliGWLMyb3I1s1+zTh6JLJ+xnD7tBampjBCyhg/HQnfE6Ljo/JnDAwIDTGCSkzdxiWirL7TA9+WxMrq5D1Nbp4V/nZEwx/Oi1EKnaHSUztx/bhFfgozq0Q5SKFPBLIE+Vr2w0aF7efAsN6zIOsXRDeIkqVWonawfNNc6HYo9EO1dOjeSQhu9XZXtwnLMAun+817i8eUmZ8873ZkNGOh3RgkU+OvHA+Bwx+HcQfbChSG+vHoQbELzA9sKs+3LfvLUMOiNvYIXoyUlcK6krb3jvHNRV3UP30YsjLoQcNhk5CP2+AIyCr5X1YwwvJdldU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

